### PR TITLE
Update Error.php

### PR DESCRIPTION
**Pull request by loco8878**
use constructor for error parameters

### CODE REVIEW

**Comment by coderbyheart** [comment]
`__construct` is not supported on PHP 4.

**Comment by loco8878** [comment]
the cache dosnt work with pear 1.10.0

**Comment by coderbyheart** [comment]
What is the problem?

**Comment by loco8878** [comment]
PEAR_Error dosnt exist anymore in PEAR 1.10.0

**Comment by cweiske** [comment]
PEAR 1.10.1 dropped support for PHP4 and changed constructor names to `__construct`. Thus Cache_Error's call to `parent::PEAR_Error` fails now.

It's time to drop PHP4 support on Cache, too.

What needs to be changed is renaming the `Cache_Error` method to `__construct`, too.

**Comment by coderbyheart** [comment]
IMO there are far better cache libraries for PHP5 so there is no need to make Cache_Lite support newer versions.

**Comment by cweiske** [comment]
1. It's about Cache, not Cache_Lite
2. People use the libraries, sometimes since half a dozen years. We should keep it working with the latest PEAR. I can do the update and the release.

**Comment by coderbyheart** [comment]
Oh. I'm terribly sorry! I've missed that detail ...

**Comment by cweiske** [comment]
I've just released [PEAR 1.10.1](http://pear.php.net/package/PEAR/download/1.10.1) which adds the old `PEAR_Error` method for backwards compatibility - other packages also have the same problem, e.g. [Net_LDAP2](http://pear.php.net/bugs/bug.php?id=20969).

@loco8878: Try to update PEAR and check if the problem is gone
@coderbyheart: The issue in `Cache` should nevertheless be fixed.

**Comment by CloCkWeRX** [comment]
For interest, fixed up travis on this package so we can at least tell if the build is happy/not.

**Comment by ashnazg** [comment]
Handled in #3

**Pull request closed without merging**
